### ISSUE TITLE
Chaning worlds

### ISSUE THREAD

**Issue by MrPesee** [MyzelYam/SuperVanish#1]
Well i have a problem with this plugin, when i change worlds i get automaticcly the vanish
so when i want to get rid of the vanish i have to do /sv but a message like MrPesee left the games comes, so it looks very bad, and players are like wtf... What i want is to get rid of that or make a silent command like /sv silent and no message comes up.

**Comment by MyzelYam** [comment]
duplicate; please either use github or spigot to report the problem, not both. responded on spigot.
