### ISSUE TITLE
Error with latest version of Spigot (1.12)

### ISSUE THREAD

**Issue by Foorack** [MyzelYam/SuperVanish#12]
> [20:01:52 INFO]: [SuperVanish] Enabling SuperVanish v5.8.4
> [20:01:52 ERROR]: Error occurred while enabling SuperVanish v5.8.4 (Is it up to date?)
> java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfigurati
> on;
>         at de.myzelyam.supervanish.config.MessagesFile.<init>(MessagesFile.java:34) ~[?:?]
>         at de.myzelyam.supervanish.SuperVanish.prepareConfig(SuperVanish.java:138) ~[?:?]
>         at de.myzelyam.supervanish.SuperVanish.onEnable(SuperVanish.java:102) ~[?:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot_ckc.jar:git-Spigot-ede465d-bb4ae3b]
>         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot_ckc.jar:git-Spigot-ede465d-bb4ae3b]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot_ckc.jar:git-Spigot-ede465d-bb4ae3b]
>         at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot_ckc.jar:git-Spigot-ede465d-bb4ae3b]
>         at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot_ckc.jar:git-Spigot-ede465d-bb4ae3b]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot_ckc.jar:git-Spigot-ede465d-bb4ae3b]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot_ckc.jar:git-Spigot-ede465d-bb4ae3b]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot_ckc.jar:git-Spigot-ede465d-bb4ae3b]
>         at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot_ckc.jar:git-Spigot-ede465d-bb4ae3b]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot_ckc.jar:git-Spigot-ede465d-bb4ae3b]

**Comment by MyzelYam** [comment]
still happening with the latest version?
