### ISSUE TITLE
the /sv command will not work

### ISSUE THREAD

**Issue by npritzer** [MyzelYam/SuperVanish#14]
I am on my 1.12 server and I have SuperVanish installed, when I do /sv nothing hapens and when I do /sv reload it says, "An Internal Server Error Has Occured".  What do I do to fix it and do you need a list of what other plugins I am using?

**Comment by npritzer** [comment]
Just noticed in console that it says to give you this information; https://pastebin.com/Jq8BTpL0

The link is the console report

**Comment by MyzelYam** [comment]
Any errors on startup? Are you using the latest version?

**Comment by npritzer** [comment]
I am using the latest version, I will check if there are any errors on startup

**Comment by npritzer** [comment]
The only error is;

[SuperVanish] Enabling SuperVanish v5.9.1
17.06 15:59:58 [Server] ERROR Error occurred while enabling SuperVanish v5.9.1 (Is it up to date?)
17.06 15:59:58 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
17.06 15:59:58 [Server] INFO at de.myzelyam.supervanish.config.MessagesFile.<init>(MessagesFile.java:34) ~[?:?]
17.06 15:59:58 [Server] INFO at de.myzelyam.supervanish.SuperVanish.prepareConfig(SuperVanish.java:142) ~[?:?]
17.06 15:59:58 [Server] INFO at de.myzelyam.supervanish.SuperVanish.onEnable(SuperVanish.java:101) ~[?:?]

**Comment by npritzer** [comment]
ok, I know why it is happening, I install plugins through my server provider and the latest one is 5.9.1.

**Comment by npritzer** [comment]
thank you for your help!
