### ISSUE TITLE
Technical basics about SuperVanish and PremiumVanish

### ISSUE THREAD

**Issue by EvilOlaf** [MyzelYam/SuperVanish#15]
Hey there,

I am interested in if the technical base for hiding players are the same in both SuperVanish and PremiumVanish. 

The description of PremiumVanish tells me this: `Since PremiumVanish uses ProtocolLib to hide players on packet level, it's virtually impossible to know that a vanished player is on the server if you're not supposed to know.`

Since PremiumVanish is obviously an improved version of SuperVanish I am curios if SuperVanish uses the same base technique even though this is not stated especially within the plugin description of SuperVanish.

Thanks for reading.
Olaf

**Comment by MyzelYam** [comment]
Both plugins use the BukkitAPI to hide players, however PremiumVanish also uses ProtocolLib to cancel packets of vanished players sent to other players so PremiumVanish has that second layer of protection on top of the Bukkit one.

**Comment by EvilOlaf** [comment]
Alright. Thank you.
