### ISSUE TITLE
Can't Compile on Windows

### ISSUE THREAD

**Issue by CDAGaming** [MyzelYam/SuperVanish#18]
@MyzelYam 

[ERROR] Failed to execute goal on project SuperVanish: Could not resolve dependencies for project de.myzelyam:SuperVanish:jar:5.10.0: The following artifacts could not be resolved: com.comphenix.protocol:ProtocolLib:jar:4.0.0-SNAPSHOT, org.spigotmc:spigot:jar:1.10-R0.1-SNAPSHOT, ca.jamiesinn.trailgui:TrailGUI:jar:1.0, org.dynmap:Dynmap:jar:1.0: Failure to find com.comphenix.protocol:ProtocolLib:jar:4.0.0-SNAPSHOT in https://hub.spigotmc.org/nexus/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of spigot-repo has elapsed or updates are forced -> [Help 1]

**Comment by CDAGaming** [comment]
It also appears Lib's Disquises is now a premium Dependency, as i discovered while i tried to update dependencies.

Link: https://www.spigotmc.org/resources/libs-disguises.32453/

**Comment by CDAGaming** [comment]
After Updating Some Dependencies:

[ERROR] Failed to execute goal on project SuperVanish: Could not resolve dependencies for project de.myzelyam:SuperVanish:jar:5.10.0: The following artifacts could not be resolved: com.comphenix.protocol:ProtocolLib:jar:4.0.0-SNAPSHOT, org.spigotmc:spigot:jar:1.10-R0.1-SNAPSHOT, ru.tehkode:PermissionsEx:jar:1.23.4: Failure to find com.comphenix.protocol:ProtocolLib:jar:4.0.0-SNAPSHOT in https://hub.spigotmc.org/nexus/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of spigot-repo has elapsed or updates are forced -> [Help 1]

**Comment by CDAGaming** [comment]
Deps Failed:

Before: ProtocolLib, Spigot, TrailGUI, Dynmap
After: ProtocolLib, Spigot, PermissionsEx

Am seeing if i can fix this myself. If i find a way to do so, ill close this and make a pr possibly

**Comment by MyzelYam** [comment]
No idea why it's not working, would be glad if someone else knows how to fix it though.

**Comment by CDAGaming** [comment]
Well @MyzelYam Can you tell me how you compile it

For me, i run mvn install -B

I managed to fix some of the issued, but unfortunatly i couldnt fix ProtocolLib
Ill make a PR to fix some of the errors

**Comment by CDAGaming** [comment]
@MyzelYam How/What command do you run to compile supervanish, maybe im just running the wrong command to compile

**Comment by MyzelYam** [comment]
Thanks for your effort. I've removed and replaced some dependencies in the latest commits to finally make maven compilation work, seems like things were just conflicting. I've always been using IntelliJ artifacts for compilation, but now both should work.

**Comment by CDAGaming** [comment]
Can Confirm Working, Thanks :)
