### ISSUE TITLE
Action Bar Doesn't Display 5.10.0

### ISSUE THREAD

**Issue by FrostTaco** [MyzelYam/SuperVanish#19]
In 5.10.0, when vanished(in any way, whether its /sv or just joining the game with autovanish) the action bar never shows for any players.

**Comment by MyzelYam** [comment]
Are you using ProtocolLib?  It works fine on my 1.12.1 server.

**Comment by FrostTaco** [comment]
I don't have ProtocolLib, and my server is 1.12

**Comment by MyzelYam** [comment]
You need ProtocolLib for the action bars to show up.
