### ISSUE TITLE
Needing help

### ISSUE THREAD

**Issue by motasim1** [MyzelYam/SuperVanish#21]
Hello,

So I am trying to build some plugins for my server but I am stuck. I have coded alot of
things in the past in JS, so I do have some experience. I want now to code in Java to make some
plugins, but I get errors the whole time. I am trying to make a vanish plugin. I would really
appreciate it if you could help me. 

Thank you for reading this!

~Motasim

**Comment by MyzelYam** [comment]
I recommend getting a java book or something similar, however this has nothing to do with supervanish.
