### ISSUE TITLE
Exclude vanished players from the server query list

### ISSUE THREAD

**Issue by esejuli94** [MyzelYam/SuperVanish#23]
Hey, I write this because I'd like to add a new feature for your great plugin.

Did you think about to filter vanished players from a query? I mean, by now, if server receives a ping, it sends the entire player list, what about if you remove the players who are vanished?

I've read about this and you can use the iterator of [ServerListPingEvent](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/server/ServerListPingEvent.html#iterator()) to remove these players. Seems very simple.

I think it could be a cool feature to completely hide vanished players. 

Thanks in advance, julito.

**Comment by MyzelYam** [comment]
It's already intercepting server pings using ProtocolLib which allows it to change the amount of online players as well
