### ISSUE TITLE
Invisable to others bug

### ISSUE THREAD

**Issue by RainOfPain125** [MyzelYam/SuperVanish#25]
After disabling SV people still don't see me untill they relog. Is that a bug or is that just a side-effect

https://pastebin.com/e2kfq6u5

**Comment by MyzelYam** [comment]
It's not a side-effect, it shouldn't happen. Are you sure that Essentials's vanish is turned off (/ev)? Does this happen on a plain server with just SV and ProtocolLib?

**Comment by RainOfPain125** [comment]
I have essentialls but we aren't using /ev or /v.

We have a wide array of plugins, but I don't see how any of them could produce a problem like this

AreaShop, Auctions, AutoSave, BlowableObsidians, BuycraftX, CFD, Chairs, ChatFeelings, ChestShop, Citizens, CombatLogX, CompatNoCheatPlus, CoreProtect, CrazyCrates, EpicRename, Essentials, EssentialsChat, FactionChat, Factions, HolographicDisplays, HolographicScoreboard, InfoBook, LimitCrafting, LuckPerms, MassiveBooks, MassiveCore, mcMMO, MessageAnnouncer, MobArena, Multiverse-Core, NoCheatPlus, OldCombatMechanics, Orebfuscator4, PerWorldInventory, PlayerHeads, PlayTime, ProtocolLib, ServerListPlus, ShulkerBlock, SilkSpawners, SimpleBackup, SuperbVote, SuperTrails, SuperVanish, Tablist, Vault, Votifier, WarningCategories, Wild, WorldEdit, WorldGuard

**Comment by MyzelYam** [comment]
I dont know which ones could cause such an issue. You can try removing them one by one on a copy of your server to find out the cause.
