### ISSUE TITLE
Add permission for chest interaction 

### ISSUE THREAD

**Issue by madtomic** [MyzelYam/SuperVanish#29]
Can you add a permission to block players from taking stuff out of chests while in vanish mode?

**Comment by MyzelYam** [comment]
Unfortunately SuperVanish doesnt have those kinds of restrictive options. PremiumVanish has though, so you can take a look at it if you want. I don't think I'll add this to SuperVanish since I'd like to keep the gap between the amount of features of PremiumVanish and SuperVanish.
