### ISSUE TITLE
Support for DiscordSRV anytime soon?

### ISSUE THREAD

**Issue by RainOfPain125** [MyzelYam/SuperVanish#30]
DiscordSRV claims on their plugin page that their plugin is compatible with SV, yet it doesn't appear so. When doing /sv in game it does the usual "user has left the game" but it does not say this in the connected discord chat - which kinda ruins the point

DiscordSRV claims that this is not their fault, so I came here to talk about it.

**Comment by MyzelYam** [comment]
DiscordSRV hides real join/quit messages of vanished players, but it doesnt broadcast fake ones when you vanish/reappear. To achieve that you can use PremiumVanish to execute DiscordSRV commands automatically whenever you vanish/reappear, or you can use Bukkit's aliases file to achieve a similar effect with SuperVanish.
