### ISSUE TITLE
/sv works but i dont stay invisible

### ISSUE THREAD

**Issue by darealHeroBrine** [MyzelYam/SuperVanish#32]
Hello,
my supervanish plugin works fully excempt i dont stay in invisible after i move i have checked the dependicyes all the same version and same version for my server can any one help me fix this i even gotten premiumvanish but that doesnt work either.

**Comment by MyzelYam** [comment]
Hey,
Please message me on Spigot for PremiumVanish support. Regarding SuperVanish, could you please provide more information? What is the output of /sv stacktrace, are there any errors in the console, this it happen without any other plugins but ProtocolLib installed?
