### ISSUE TITLE
Fresh install

### ISSUE THREAD

**Issue by RainOfPain125** [MyzelYam/SuperVanish#39]
https://pastebin.com/0KArD60i

Installed SV and ProtocolLib for 1.7.10

**Comment by MyzelYam** [comment]
Seems like your ProtocolLib is broken, are you using the proper version of it that supports 1.7.10? If you dont need them, you can also disable the server list features in SVs config file.

**Comment by RainOfPain125** [comment]
I couldn't find the proper version for ProtocolLib, do you mind sending a link?

I used the 1.7.10 ver of it labled v3.7.0 here - https://github.com/dmulloy2/ProtocolLib/releases/tag/3.7.0

**Comment by Gusted** [comment]
@RainOfPain125 Supervanish is fine but protocolib has some issued open an issue ticket at https://github.com/aadnk/ProtocolLib They can help you further with this problem
