### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by games647** [MyzelYam/SuperVanish#4]
Do you have any plans on providing this project as a maven project. It might be helpful for plugins which depend on this plugin. Then this dependency could be automatically downloaded and so very easy to setup.

**Comment by MyzelYam** [comment]
I would however SuperVanish has lots of dependencies of which some dont have a maven repo.

**Comment by games647** [comment]
Plugins which has a maven repo:
ProtocolLib [X]
LibsDisguises [X]
DisguiseCraft [X]
dynmap [X]
Essentials [X]
TrailGUI [X] but seems to be down
EnjinMinecraftPlugin [ ]
Citizens [X]
SuperTrails [ ]

For the remaining three plugins you could declare them with system scope. Just a thought.

**Comment by RickyB98** [comment]
I just cloned the repository, planning to fork it to make some adjustments and meanwhile I'm integrating maven. It would be nice if you could link to the artifacts you use to compile the project.
