### ISSUE TITLE
When joining vanished, (most times) Night Vision isn't applied. 

### ISSUE THREAD

**Issue by NinoM4ster** [MyzelYam/SuperVanish#40]
To receive the effect, I have to type /v twice.

Minecraft version 1.13.2 (Spigot)
SuperVanish version 6.1.0

I haven't tested without any other plugins, but I may if you want.

Here are some screenshots:
![image](https://user-images.githubusercontent.com/8485761/48726763-7ec45880-ec17-11e8-9d5b-15aeb50f94fd.png)
![image](https://user-images.githubusercontent.com/8485761/48726775-8683fd00-ec17-11e8-99dc-9994ba0cec34.png)

Thank you!

**Comment by Gusted** [comment]
@NinoM4ster I think this it's the Autmereloaded because you joined vanish but AuthMereLoaded removes you potions when joining the server and you need to log in. Or just do twice /v or open an issue at https://github.com/AuthMe/AuthMeReloaded
