### ISSUE TITLE
(enhancement) Toggle command for join / leave messages

### ISSUE THREAD

**Issue by Martijnkop** [MyzelYam/SuperVanish#42]
There's some situations in which I would prefer not showing join / leave messages (and people dissapearing in tab) when going in and out of vanish. Could it be possible to add a command to sv (or premiumvanish) to quickly enable / disable / toggle these options? Would be very appreciated :D

**Comment by Martijnkop** [comment]
also, sorry if I put this in the wrong place, I don't know where else to put it :3

**Comment by MyzelYam** [comment]
You can use /sv -s or /pv -s to vanish/reappear silently or you can turn off fake join/quit messages in the config file. With PV you can also make yourself visible in tab using a config option.
