### ISSUE TITLE
[API] Event for Vanish Scoreboard (enabled/disabled)

### ISSUE THREAD

**Issue by Drc-DEV** [MyzelYam/SuperVanish#43]
In order for scoreboard plugins to add compatibility with supervanish/premiumvanish's scoreboard, we need an event that fires when the scoreboard is activated and deactivated for a vanished player.

**Comment by MyzelYam** [comment]
Hey, there currently is no event for that but you can use the (monitor priority) PlayerHideEvent, PlayerShowEvent and PlayerJoinEvent with VanishAPI.isInvisible to achieve the same.
