### ISSUE TITLE
Mobs still look at vanished players

### ISSUE THREAD

**Issue by InfinityMage** [MyzelYam/SuperVanish#49]
Mobs, including villagers and sheep, look at vanished players ingame.

Server: Paper 1.14.4 v192
Plugin version: 6.1.3

**Comment by QuazArxx** [comment]
In the config.yml find the following lines:

  # Should SV prevent mobs from targeting invisible players?
  DisableMobTarget: false

Check if it's false. If it is set it to true

**Comment by MyzelYam** [comment]
Unfortunately the Bukkit API doesnt allow us to stop mob behavior that is outside of the EntityTargetEvent's control and using ProtocolLib for this is outside of SuperVanish's scope, which is supposed to be lightweight (Though I would accept solid PRs). You should be able to work around this by using spectator mode, but that's not a real solution obviously.
