### ISSUE TITLE
Receiving Same Error Over and Over

### ISSUE THREAD

**Issue by QuazArxx** [MyzelYam/SuperVanish#50]
https://pastebin.com/Ja1QZTqf

I'm currently running the paper 214. The message on the bottom above the bar showing that you're in vanish not showing anymore. I'm assuming it's due to this error

**Comment by Cylizion** [comment]
I'm receiving this error too. Every 2-4 seconds. And the display saying if you're in vanish is not appearing. Waiting on a fix.

Running Spigot v1.14.4

**Comment by MyzelYam** [comment]
Please install the latest ProtocolLib dev-build as described in ProtocolLib's resource description!
